site_name: llm-sandbox
repo_url: https://github.com/vndee/llm-sandbox
site_url: https://vndee.github.io/llm-sandbox
site_description: LLM Sandbox is a lightweight and portable sandbox environment designed to run large language model (LLM) generated code in a safe and isolated manner using containers.
site_author: Duy Huynh
edit_uri: edit/main/docs/
repo_name: vndee/llm-sandbox
copyright: Maintained by <a href="https://vndee.com">vndee</a>.

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
      - Configuration: configuration.md
  - API Reference: modules.md
  - Contributing: contributing.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["llm_sandbox"]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2
            show_category_heading: true
            docstring_style: google
            show_if_no_docstring: true
            show_signature_annotations: true

theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vndee/llm-sandbox
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/llm-sandbox

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
